// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// nextItemEPVcpp
List nextItemEPVcpp(S4 cat_df);
RcppExport SEXP CATPack_nextItemEPVcpp(SEXP cat_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type cat_df(cat_dfSEXP);
    __result = Rcpp::wrap(nextItemEPVcpp(cat_df));
    return __result;
END_RCPP
}
// lookAheadEPVcpp
List lookAheadEPVcpp(S4 cat_df, NumericVector item);
RcppExport SEXP CATPack_lookAheadEPVcpp(SEXP cat_dfSEXP, SEXP itemSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< S4 >::type cat_df(cat_dfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type item(itemSEXP);
    __result = Rcpp::wrap(lookAheadEPVcpp(cat_df, item));
    return __result;
END_RCPP
}
