# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nextItemEPVcpp <- function(cat_df) {
    .Call('CATPack_nextItemEPVcpp', PACKAGE = 'CATPack', cat_df)
}

lookAheadEPVcpp <- function(cat_df, item) {
    .Call('CATPack_lookAheadEPVcpp', PACKAGE = 'CATPack', cat_df, item)
}

